name: Build and Release CV

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Compile CV
        run: |
          pdflatex -interaction=nonstopmode cv.tex
          pdflatex -interaction=nonstopmode cv.tex  # Run twice for references
          
      - name: Check if PDF was created
        run: |
          if [ ! -f cv.pdf ]; then
            echo "PDF was not created"
            exit 1
          fi
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: cv.pdf
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 